gitSourceBranch = "main"
changelog = true

[[classOrder]]
classes = ["Inputter"]

[[classOrder]]
section = "Triggers"
classes = ["MULTIPLE_PRESS", "PRESS", "HOLD"]

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2025 Adam Mills."
