[package]
name = "adammillsy/inputter"
description = "A light-weight cross-platform input manager"
version = "0.0.3"
license = "MIT"
authors = ["Adam Mills"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
